// @ts-check
// Tests for bin/generate.js run as a process: install.sh writes the generated aster.d files before Asterisk starts, because
// Asterisk rejects a whole file whose #include target is missing.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, describe, test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { generateAll } from '../src/config/generators.js';
import { validate } from '../src/config/registry.js';

const GENERATE = fileURLToPath(new URL('../bin/generate.js', import.meta.url));
const root = mkdtempSync(join(tmpdir(), 'aster-generate-'));
after(() => rmSync(root, { recursive: true, force: true }));

/**
 * An ASTER_HOME as install.sh has it when it runs this: the tree and the secrets exist, aster.d is empty.
 * @param {string} name
 * @param {string} [registry]  the text of config/aster.yaml; an empty string leaves the file out entirely
 */
function makeHome(name, registry = '') {
  const home = join(root, name);
  mkdirSync(join(home, 'config', 'asterisk', 'aster.d'), { recursive: true });
  mkdirSync(join(home, 'state'), { recursive: true });
  writeFileSync(join(home, 'config', 'secrets.env'), 'ASTER_AMI_SECRET=ami\n', { mode: 0o600 });
  if (registry !== '') writeFileSync(join(home, 'config', 'aster.yaml'), registry);
  return home;
}

/** @param {string} home @param {string[]} [args] */
const run = (home, args = []) =>
  spawnSync(process.execPath, [GENERATE, ...args], { encoding: 'utf8', env: { ...process.env, ASTER_HOME: home } });

const read = (/** @type {string} */ home, /** @type {string} */ name) =>
  readFileSync(join(home, 'config', 'asterisk', 'aster.d', name), 'utf8');

const FIVE = ['globals.conf', 'modems.conf', 'phones.conf', 'quectel-devices.conf', 'dongle-devices.conf'];

describe('bin/generate.js', () => {
  test('writes exactly what an apply would write, for the registry that is there', () => {
    const registry = [
      'version: 1',
      'modems:',
      '  - id: gsm1',
      '    driver: quectel',
      '    imei: "867435040012345"',
      '    enabled: true',
      '    ring: ["501"]',
      'phones:',
      '  - { number: "501", secret: "s501", outbound: gsm1 }',
      '',
    ].join('\n');
    const home = makeHome('with-modem', registry);
    const result = run(home);
    assert.equal(result.status, 0, result.stderr);

    // The same function the registry-apply operation uses: these bytes and an apply's cannot drift.
    const expected = generateAll(validate({
      version: 1,
      modems: [{ id: 'gsm1', driver: 'quectel', imei: '867435040012345', enabled: true, ring: ['501'] }],
      phones: [{ number: '501', secret: 's501', outbound: 'gsm1' }],
    }));
    for (const name of FIVE) assert.equal(read(home, name), expected[`aster.d/${name}`], name);
    assert.match(read(home, 'globals.conf'), /^GSM1=Quectel\/gsm1$/m);
    assert.match(read(home, 'quectel-devices.conf'), /^\[gsm1\]$/m);
    assert.match(read(home, 'phones.conf'), /^\[501\]\(aster-phone\)$/m);
  });

  test('an appliance with no registry yet is the empty registry, not an error', () => {
    const home = makeHome('no-registry');
    const result = run(home);
    assert.equal(result.status, 0, result.stderr);
    // Every file exists — that is the whole point, since Asterisk refuses a file whose include is missing — and the two
    // device lists hold nothing but their header.
    for (const name of FIVE) assert.match(read(home, name), /^; GENERATED by aster/);
    assert.equal(read(home, 'quectel-devices.conf').split('\n').filter((line) => line.startsWith('[')).length, 0);
    assert.match(read(home, 'modems.conf'), /\[aster-hangup\]/);
  });

  test('a second run writes nothing, and --force rewrites anyway', () => {
    const home = makeHome('twice');
    assert.equal(run(home).status, 0);
    const before = FIVE.map((name) => statSync(join(home, 'config', 'asterisk', 'aster.d', name)).mtimeMs);

    const second = run(home);
    assert.equal(second.status, 0, second.stderr);
    assert.match(second.stdout, /0 of 5 file\(s\) written/);
    assert.deepEqual(FIVE.map((name) => statSync(join(home, 'config', 'asterisk', 'aster.d', name)).mtimeMs), before,
      'an unchanged file must not be rewritten: on an SD card a write for nothing is wear');

    const forced = run(home, ['--force']);
    assert.equal(forced.status, 0, forced.stderr);
    assert.match(forced.stdout, /5 of 5 file\(s\) written/);
  });

  test('a registry that does not validate stops it, names the problems and writes nothing', () => {
    const home = makeHome('broken', 'version: 1\nmodems:\n  - id: "NOT VALID"\n    driver: quectel\n    imei: "1"\n    enabled: true\nphones: []\n');
    const result = run(home);
    assert.equal(result.status, 2);
    assert.match(result.stderr, /is invalid, so the generated files cannot be written/);
    assert.match(result.stderr, /modems\[0\]\.id/);
    for (const name of FIVE) {
      assert.throws(() => read(home, name), { code: 'ENOENT' }, `${name} must not be written from a registry that does not validate`);
    }
  });

  test('--quiet prints nothing when there is nothing to say', () => {
    const home = makeHome('quiet');
    const result = run(home, ['--quiet']);
    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, '');
  });
});
