// @ts-check
// Generates config/asterisk/aster.d/* deterministically from a validated registry. Only values the registry rules
// restrict to safe characters are written; labels never are.
import { createHash } from 'node:crypto';
import { isUnmapped, validate } from './registry.js';

/** @typedef {import('./registry.js').Registry} Registry */
/** @typedef {import('./registry.js').Modem} Modem */

/** First line of globals.conf, modems.conf and phones.conf. */
export const HEADER = '; GENERATED by aster from aster.yaml — do not edit.';
/** First line of the two device files. */
export const DEVICES_HEADER = '; GENERATED by aster from aster.yaml — do not edit; edit aster.yaml or use the UI.';

/** Names of the generated files relative to config/asterisk, in the order generateAll returns them. */
export const GENERATED_FILES = Object.freeze(['aster.d/globals.conf', 'aster.d/modems.conf', 'aster.d/phones.conf',
  'aster.d/quectel-devices.conf', 'aster.d/dongle-devices.conf']);

/** Channel technology each driver registers: the prefix of its dial strings. */
const TECHNOLOGY = { quectel: 'Quectel', dongle: 'Dongle' };
/** Dial timeout of aster-out-<id> in seconds (ring_timeout belongs to the ring group of incoming calls). */
export const OUTBOUND_DIAL_TIMEOUT = 120;
/** Column at which the comments after context headers start in modems.conf. */
const COMMENT_COLUMN = 38;

/** aster-in-<id> after its header; placeholders %ID% (modem id) and %TARGET% (the context the call is sent to). */
const INGRESS = [
  'exten => s,1,Set(__ASTER_MODEM=%ID%)',
  ' same => n,Set(__ASTER_DID=)',
  ' same => n,Set(CHANNEL(hangup_handler_push)=aster-hangup,s,1)',
  ' same => n,Goto(%TARGET%,s,1)',
  'exten => _[+0-9].,1,Set(__ASTER_MODEM=%ID%)',
  ' same => n,Set(__ASTER_DID=${EXTEN})',
  ' same => n,Set(CHANNEL(hangup_handler_push)=aster-hangup,s,1)',
  ' same => n,Goto(%TARGET%,s,1)',
  'exten => sms,1,System(/usr/local/bin/aster-emit sms %ID% "${UNIQUEID}" "${BASE64_ENCODE(x${CALLERID(num)})}" "${SMS_BASE64}" "${BASE64_ENCODE(x${SMS_TS})}")',
  ' same => n,ExecIf($["${SYSTEMSTATUS}"!="SUCCESS"]?Log(ERROR,aster-emit sms %ID% failed: ${SYSTEMSTATUS}))',
  ' same => n,Hangup()',
  'exten => report,1,System(/usr/local/bin/aster-emit sms-report %ID% "${UNIQUEID}" "${BASE64_ENCODE(x${SMS_REPORT_PAYLOAD})}" "${SMS_REPORT_TYPE}" "${SMS_REPORT_SUCCESS}" "${BASE64_ENCODE(x${SMS_REPORT_TS})}" "${BASE64_ENCODE(x${SMS_REPORT_DT})}" "${BASE64_ENCODE(x${SMS_REPORT})}")',
  ' same => n,Hangup()',
  'exten => ussd,1,Hangup()',
];
/**
 * Jitter buffer on the phone's channel, since a modem plays late RTP packets as gaps. The kind comes from the
 * hand-owned global PHONE_JITTERBUFFER (`adaptive`, `fixed`; empty: none).
 */
const JITTERBUFFER = 'ExecIf($["${PHONE_JITTERBUFFER}"!=""]?Set(JITTERBUFFER(${PHONE_JITTERBUFFER})=default))';
/** The context Dial's b() runs on a called phone, and the option that names it. */
const JITTERBUFFER_CONTEXT = 'aster-jitterbuffer';
const RING_OPTIONS = `mb(${JITTERBUFFER_CONTEXT}^s^1)`;
/** aster-out-<id> after its header; placeholders %GLOBAL% (the modem's global) and %TIMEOUT% (OUTBOUND_DIAL_TIMEOUT). */
const OUTBOUND = [
  `exten => _+X.,1,${JITTERBUFFER}`,
  ' same => n,Dial(${%GLOBAL%}/${EXTEN},%TIMEOUT%)',
  ' same => n,Hangup()',
  `exten => _*X.,1,${JITTERBUFFER}`,
  ' same => n,Dial(${%GLOBAL%}/${EXTEN:1},%TIMEOUT%)',
  ' same => n,Hangup()',
];
/** The pre-dial handler of the ring groups. */
const JITTERBUFFER_HANDLER = [
  `[${JITTERBUFFER_CONTEXT}]`,
  `exten => s,1,${JITTERBUFFER}`,
  ' same => n,Return()',
];
/** The shared hangup handler every carrier call pushes. */
const HANGUP = [
  '[aster-hangup]',
  'exten => s,1,System(/usr/local/bin/aster-emit call-end "${ASTER_MODEM}" "${UNIQUEID}" "${BASE64_ENCODE(x${CALLERID(num)})}" "${BASE64_ENCODE(x${ASTER_DID})}" "${BASE64_ENCODE(x${DIALSTATUS})}" "${BASE64_ENCODE(x${ANSWEREDTIME})}" "${BASE64_ENCODE(x${CDR(disposition)})}" "${BASE64_ENCODE(x${HANGUPCAUSE})}" "${BASE64_ENCODE(x${DIALEDTIME})}")',
  ' same => n,Return()',
];

/** @param {readonly string[]} lines */
const fileText = (lines) => `${lines.join('\n')}\n`;
/** @param {string} header @param {string} comment */
const commented = (header, comment) => `${header.padEnd(COMMENT_COLUMN)}; ${comment}`;
/**
 * @param {readonly string[]} lines
 * @param {Record<string, string>} values placeholder → value (a function replacer, so "$" in a value is never special)
 */
const fill = (lines, values) =>
  lines.map((line) => Object.entries(values).reduce((out, [placeholder, value]) => out.replaceAll(placeholder, () => value), line));

/**
 * ALSA card id that install/udev/alsa-name gives the UAC sound card of a Quectel modem on USB port `usbPort`:
 * q_<port with - and. replaced by _>, or qh_<first 12 hex digits of sha1(port)> when that is longer than 15 characters
 * (the kernel's limit for a card id).
 * @param {string} usbPort
 */
export function alsaCardId(usbPort) {
  const name = `q_${usbPort.replaceAll(/[-.]/g, '_')}`;
  return name.length <= 15 ? name : `qh_${createHash('sha1').update(usbPort).digest('hex').slice(0, 12)}`;
}

/**
 * aster.d/globals.conf, included inside [globals] of extensions.conf: one global per modem, GSM1=Quectel/gsm1.
 * @param {Registry} reg
 */
export function globals(reg) {
  return fileText([HEADER, ...reg.modems.map((modem) => `${modem.id.toUpperCase()}=${TECHNOLOGY[modem.driver]}/${modem.id}`)]);
}

/**
 * aster.d/modems.conf: per modem the carrier ingress aster-in-<id> (into incoming_context, else aster-ring-<id>), the
 * ring group aster-ring-<id> (only when incoming_context is null; with ring: [] it hangs up at once, so the call is
 * recorded as missed), the outbound patterns aster-out-<id> and the endpoint context aster-phones-<id>; then the shared
 * aster-phones-internal, aster-jitterbuffer (JITTERBUFFER above) and aster-hangup.
 * @param {Registry} reg
 */
export function modems(reg) {
  const lines = [HEADER];
  for (const modem of reg.modems) {
    const { id } = modem;
    lines.push(commented(`[aster-in-${id}]`, 'carrier ingress (driver context)'),
      ...fill(INGRESS, { '%ID%': id, '%TARGET%': modem.incoming_context ?? `aster-ring-${id}` }));
    if (modem.incoming_context === null) {
      lines.push('', commented(`[aster-ring-${id}]`, 'generated from modems[].ring (used when incoming_context is null)'));
      if (modem.ring.length === 0) {
        lines.push('exten => s,1,Hangup()');
      } else {
        lines.push(`exten => s,1,Dial(${modem.ring.map((number) => `PJSIP/${number}`).join('&')},${modem.ring_timeout},${RING_OPTIONS})`,
          ' same => n,Hangup()');
      }
    }
    lines.push('', `[aster-out-${id}]`, ...fill(OUTBOUND, { '%GLOBAL%': id.toUpperCase(), '%TIMEOUT%': String(OUTBOUND_DIAL_TIMEOUT) }),
      '', commented(`[aster-phones-${id}]`, `endpoint context for phones with outbound: ${id}`), 'include => internal',
      `include => aster-out-${id}`, '');
  }
  lines.push(commented('[aster-phones-internal]', 'endpoint context for phones with outbound: null'), 'include => internal', '',
    ...JITTERBUFFER_HANDLER, '', ...HANGUP);
  return fileText(lines);
}

/**
 * aster.d/phones.conf: endpoint, auth and aor of every phone, inheriting the templates of the hand-owned pjsip.conf. The
 * endpoint context is phones[].context, else aster-phones-<outbound>, else aster-phones-internal.
 * @param {Registry} reg
 */
export function phones(reg) {
  const lines = [HEADER];
  for (const [index, phone] of reg.phones.entries()) {
    const { number } = phone;
    if (index > 0) lines.push('');
    lines.push(`[${number}](aster-phone)`, `context=${phone.context ?? `aster-phones-${phone.outbound ?? 'internal'}`}`, `auth=${number}`,
      `aors=${number}`, `callerid=${number}`);
    if (phone.direct_media) lines.push('direct_media=yes');
    // Asterisk reads "=>" as the separator, so "password=>x" would lose the ">"; after "= " the value is read whole.
    lines.push(`[${number}](aster-auth)`, `username=${number}`, phone.secret.startsWith('>') ? `password= ${phone.secret}` : `password=${phone.secret}`,
      `[${number}](aster-aor)`);
  }
  return fileText(lines);
}

/**
 * The initstate of a modem's device section: stop only when unmapped. A disabled modem is started with its radio off,
 * since a stopped device's modem would stay registered on the network and keep taking calls.
 * @param {Modem} modem
 * @returns {'start' | 'stop'}
 */
export const initstateOf = (modem) => (!modem.enabled || !isUnmapped(modem) ? 'start' : 'stop');

/**
 * The radio setting of a modem's device section: `on` when enabled, `off` when disabled. The patched drivers send AT+CFUN=1
 * or AT+CFUN=0 at every connect; `off` then keeps the device connected and idle.
 * @param {Pick<Modem, 'enabled'>} modem
 * @returns {'on' | 'off'}
 */
export const radioOf = (modem) => (modem.enabled ? 'on' : 'off');

/**
 * The device sections of one driver: context, group (omitted when null), imei — or data and audio when ports is set —,
 * quec_uac and alsadev for a quectel modem with uac and usb_port, initstate and radio (initstateOf, radioOf). An unmapped
 * modem (uac without usb_port) gets no quec_uac: chan_quectel skips a device whose quec_uac has no alsadev.
 * @param {Registry} reg
 * @param {Modem['driver']} driver
 */
function devices(reg, driver) {
  const lines = [DEVICES_HEADER];
  for (const modem of reg.modems) {
    if (modem.driver !== driver) continue;
    if (lines.length > 1) lines.push('');
    lines.push(`[${modem.id}]`, `context = aster-in-${modem.id}`);
    if (modem.group !== null) lines.push(`group = ${modem.group}`);
    if (modem.ports === null) lines.push(`imei = ${modem.imei}`);
    else lines.push(`data = ${modem.ports.data}`, `audio = ${modem.ports.audio}`);
    if (driver === 'quectel' && modem.uac && modem.usb_port !== null) {
      lines.push('quec_uac = 1', `alsadev = plughw:CARD=${alsaCardId(modem.usb_port)}`);
    }
    lines.push(`initstate = ${initstateOf(modem)}`, `radio = ${radioOf(modem)}`);
  }
  return fileText(lines);
}

/**
 * aster.d/quectel-devices.conf, included by the hand-owned quectel.conf.
 * @param {Registry} reg
 */
export const quectelDevices = (reg) => devices(reg, 'quectel');

/**
 * aster.d/dongle-devices.conf, included by the hand-owned dongle.conf.
 * @param {Registry} reg
 */
export const dongleDevices = (reg) => devices(reg, 'dongle');

/**
 * All five files for `input`, keyed by GENERATED_FILES. The input is validated first: the files embed ids, numbers,
 * context names, secrets and device paths that only the registry rules make safe for dialplan, shell and config syntax.
 * @param {unknown} input
 * @returns {Readonly<Record<string, string>>}
 */
export function generateAll(input) {
  const reg = validate(input);
  return Object.freeze({
    'aster.d/globals.conf': globals(reg),
    'aster.d/modems.conf': modems(reg),
    'aster.d/phones.conf': phones(reg),
    'aster.d/quectel-devices.conf': quectelDevices(reg),
    'aster.d/dongle-devices.conf': dongleDevices(reg),
  });
}
